baseurl = "/"
languageCode = "en-us"
title = "HSU, Ting-Yu(Cesar)"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "MandarinGuru"
    url = "/MandarinGuru/"
[[menu.main]]
    name = "About Me"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/chekuin7"
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/hsu-ting-yu-0558b2b0/"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.png"

    [params.logo]
    url = "logoc.png"
    width = 50
    height = 50
    alt = "Logo"

